version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    #image: digitalocean.com/php
    container_name: RESTfulapp
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/app.conf/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: RESTfulwebserver
    restart: unless-stopped
    tty: true
    ports:
      # I'm using port 8888 to access docker to avoid conflict with port 80
      # in my local environment
      - "8888:8888"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: RESTfuldb
    restart: unless-stopped
    tty: true
    ports:
      # The same principle goes for mysql by using port 3307 instead of
      # default port 3306
      - "3306:3306"
    environment:
      MYSQL_DATABASE: restfulapidb
      # replace with your own mysql password here
      MYSQL_ROOT_PASSWORD: restpassword1234
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local